version: "2.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: course_management_api
    ports:
      - 9090:8080
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json
  mariadb:
    image: mariadb:10.5.5 
    container_name: mariadb
    volumes:
      - ./course.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=course_api
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080