basePath: /
info:
  contact:
    name: Mero Edu
    url: https://meroedu.com
  description: Mero Edu is a software application for the administration, documentation, tracking, reporting, automation and delivery of educational courses, training programs, or learning and development programs for school.
  license:
    name: MIT License
    url: https://github.com/meroedu/meroedu/blob/master/LICENSE
  title: Mero Edu API
  version: "0.1"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - health
swagger: "2.0"
